// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.geoskola.gsp.klase;

import com.geoskola.gsp.klase.Tocka;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tocka_Roo_Configurable {
    
    declare @type: Tocka: @Configurable;
    
}
