// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.geoskola.gsp.klase;

import com.geoskola.gsp.klase.Tocka;
import com.geoskola.gsp.klase.TockaDataOnDemand;
import com.geoskola.gsp.klase.TockaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TockaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TockaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TockaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TockaIntegrationTest: @Transactional;
    
    @Autowired
    TockaDataOnDemand TockaIntegrationTest.dod;
    
    @Test
    public void TockaIntegrationTest.testCountTockas() {
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", dod.getRandomTocka());
        long count = Tocka.countTockas();
        Assert.assertTrue("Counter for 'Tocka' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TockaIntegrationTest.testFindTocka() {
        Tocka obj = dod.getRandomTocka();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to provide an identifier", id);
        obj = Tocka.findTocka(id);
        Assert.assertNotNull("Find method for 'Tocka' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tocka' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TockaIntegrationTest.testFindAllTockas() {
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", dod.getRandomTocka());
        long count = Tocka.countTockas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tocka', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tocka> result = Tocka.findAllTockas();
        Assert.assertNotNull("Find all method for 'Tocka' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tocka' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TockaIntegrationTest.testFindTockaEntries() {
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", dod.getRandomTocka());
        long count = Tocka.countTockas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tocka> result = Tocka.findTockaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tocka' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tocka' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TockaIntegrationTest.testFlush() {
        Tocka obj = dod.getRandomTocka();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to provide an identifier", id);
        obj = Tocka.findTocka(id);
        Assert.assertNotNull("Find method for 'Tocka' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTocka(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tocka' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TockaIntegrationTest.testMergeUpdate() {
        Tocka obj = dod.getRandomTocka();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to provide an identifier", id);
        obj = Tocka.findTocka(id);
        boolean modified =  dod.modifyTocka(obj);
        Integer currentVersion = obj.getVersion();
        Tocka merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tocka' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TockaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", dod.getRandomTocka());
        Tocka obj = dod.getNewTransientTocka(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tocka' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tocka' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Tocka' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TockaIntegrationTest.testRemove() {
        Tocka obj = dod.getRandomTocka();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tocka' failed to provide an identifier", id);
        obj = Tocka.findTocka(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tocka' with identifier '" + id + "'", Tocka.findTocka(id));
    }
    
}
